const Shipments = [
  {
    containerNo: ["DEJ56KJ780", "XYZ12345JK"],
    importer: "John Doe",
    shippingLine: "Maersk",
    examinationAndCustomReleasing: "Uncleared",
    cosigneeName: "Jane Smith",
    customDocumentation: "Pending",
    portOfDischarge: "Lekki",
    shippingReleasing: "Uncleared",
    delivery: "Not yet",
    ETA: "2025-07-03",
    status: "Arrived",
    vessel: "Maersk Kampala",
    billLandingNo: "BL12345678"
  },
  {
    containerNo: ["GHT67LP900"],
    importer: "Chinedu Okoro",
    shippingLine: "MSC",
    examinationAndCustomReleasing: "Cleared",
    cosigneeName: "Ada Obi",
    customDocumentation: "Completed",
    portOfDischarge: "Apapa",
    shippingReleasing: "Cleared",
    delivery: "Completed",
    ETA: "2025-07-10",
    status: "Arrived",
    vessel: "MSC Zoe",
    billLandingNo: "BL87654321"
  },
  {
    containerNo: ["AB123CD456", "LMN987ZY654"],
    importer: "Kemi Ade",
    shippingLine: "CMA CGM",
    examinationAndCustomReleasing: "Uncleared",
    cosigneeName: "Tobi Banks",
    customDocumentation: "In Progress",
    portOfDischarge: "Tin Can",
    shippingReleasing: "Uncleared",
    delivery: "Not yet",
    ETA: "2025-07-15",
    status: "Arrived",
    vessel: "CMA CGM Benjamin Franklin",
    billLandingNo: "BL11223344"
  },
  {
    containerNo: ["JKL78MN012"],
    importer: "Ngozi Uche",
    shippingLine: "COSCO",
    examinationAndCustomReleasing: "Cleared",
    cosigneeName: "Yemi Eze",
    customDocumentation: "Completed",
    portOfDischarge: "Onne",
    shippingReleasing: "Cleared",
    delivery: "Completed",
    ETA: "2025-07-27",
    status: "Sailing",
    vessel: "COSCO Netherlands",
    billLandingNo: "BL99887766"
  },
  {
    containerNo: ["PLM45TR332"],
    importer: "Ibrahim Musa",
    shippingLine: "Hapag-Lloyd",
    examinationAndCustomReleasing: "Pending",
    cosigneeName: "Fatima Bello",
    customDocumentation: "Pending",
    portOfDischarge: "Warri",
    shippingReleasing: "Uncleared",
    delivery: "Not yet",
    ETA: "2025-07-29",
    status: "Sailing",
    vessel: "Hapag Hamburg",
    billLandingNo: "BL55667788"
  },
  {
    containerNo: ["XYZ789AB001", "QWE234CD567", "RTY890EF123"],
    importer: "Chuka Nwosu",
    shippingLine: "Evergreen",
    examinationAndCustomReleasing: "Uncleared",
    cosigneeName: "Oge Okeke",
    customDocumentation: "Started",
    portOfDischarge: "Calabar",
    shippingReleasing: "Uncleared",
    delivery: "Not yet",
    ETA: "2025-08-02",
    status: "Sailing",
    vessel: "Evergreen Marine",
    billLandingNo: "BL33445566"
  }
];

export default Shipments;
