const Shipments = [
  {
    containerNo: ["DEJ56KJ780", "XYZ12345JK"],
    importer: "John Doe",
    shippingLine: "Maersk",
    examinationAndCustomReleasing: "Uncleared",
    cosigneeName: "Jane Smith",
    customDocumentation: "Pending",
    portOfDischarge: "Lekki",
    shippingReleasing: "Uncleared",
    delivery: "Not yet",
    ETA: "2025-07-20",
    status: "In Transit",
    vessel: "Maersk Kampala",
    billLandingNo: "BL12345678"
  },
  {
    containerNo: ["GHT67LP900"],
    importer: "Chinedu Okoro",
    shippingLine: "MSC",
    examinationAndCustomReleasing: "Cleared",
    cosigneeName: "Ada Obi",
    customDocumentation: "Completed",
    portOfDischarge: "Apapa",
    shippingReleasing: "Cleared",
    delivery: "Completed",
    ETA: "2025-07-12",
    status: "Delivered",
    vessel: "MSC Zoe",
    billLandingNo: "BL87654321"
  },
  {
    containerNo: ["AB123CD456", "LMN987ZY654"],
    importer: "Kemi Ade",
    shippingLine: "CMA CGM",
    examinationAndCustomReleasing: "Uncleared",
    cosigneeName: "Tobi Banks",
    customDocumentation: "In Progress",
    portOfDischarge: "Tin Can",
    shippingReleasing: "Uncleared",
    delivery: "Not yet",
    ETA: "2025-07-25",
    status: "Awaiting Clearance",
    vessel: "CMA CGM Benjamin Franklin",
    billLandingNo: "BL11223344"
  },
  {
    containerNo: ["JKL78MN012"],
    importer: "Ngozi Uche",
    shippingLine: "COSCO",
    examinationAndCustomReleasing: "Cleared",
    cosigneeName: "Yemi Eze",
    customDocumentation: "Completed",
    portOfDischarge: "Onne",
    shippingReleasing: "Cleared",
    delivery: "Completed",
    ETA: "2025-07-10",
    status: "Delivered",
    vessel: "COSCO Netherlands",
    billLandingNo: "BL99887766"
  },
  {
    containerNo: ["PLM45TR332"],
    importer: "Ibrahim Musa",
    shippingLine: "Hapag-Lloyd",
    examinationAndCustomReleasing: "Pending",
    cosigneeName: "Fatima Bello",
    customDocumentation: "Pending",
    portOfDischarge: "Warri",
    shippingReleasing: "Uncleared",
    delivery: "Not yet",
    ETA: "2025-07-19",
    status: "In Transit",
    vessel: "Hapag Hamburg",
    billLandingNo: "BL55667788"
  },
  {
    containerNo: ["XYZ789AB001", "QWE234CD567", "RTY890EF123"],
    importer: "Chuka Nwosu",
    shippingLine: "Evergreen",
    examinationAndCustomReleasing: "Uncleared",
    cosigneeName: "Oge Okeke",
    customDocumentation: "Started",
    portOfDischarge: "Calabar",
    shippingReleasing: "Uncleared",
    delivery: "Not yet",
    ETA: "2025-07-22",
    status: "On Hold",
    vessel: "Evergreen Marine",
    billLandingNo: "BL33445566"
  },
  {
    containerNo: ["DEF34GH908"],
    importer: "Fola Adebayo",
    shippingLine: "ONE",
    examinationAndCustomReleasing: "Pending",
    cosigneeName: "Lola James",
    customDocumentation: "In Progress",
    portOfDischarge: "Port Harcourt",
    shippingReleasing: "Uncleared",
    delivery: "Not yet",
    ETA: "2025-07-23",
    status: "In Transit",
    vessel: "ONE Apus",
    billLandingNo: "BL10293847"
  },
  {
    containerNo: ["KLM5566JJ", "POI9988UU"],
    importer: "Seyi Law",
    shippingLine: "ZIM",
    examinationAndCustomReleasing: "Cleared",
    cosigneeName: "Emeka Obi",
    customDocumentation: "Completed",
    portOfDischarge: "Lekki",
    shippingReleasing: "Cleared",
    delivery: "Completed",
    ETA: "2025-07-13",
    status: "Delivered",
    vessel: "ZIM Rotterdam",
    billLandingNo: "BL77665544"
  },
  {
    containerNo: ["NMB43XY872"],
    importer: "Amina Yusuf",
    shippingLine: "Maersk",
    examinationAndCustomReleasing: "Pending",
    cosigneeName: "Rahman Musa",
    customDocumentation: "Pending",
    portOfDischarge: "Apapa",
    shippingReleasing: "Uncleared",
    delivery: "Not yet",
    ETA: "2025-07-26",
    status: "Awaiting Documents",
    vessel: "Maersk Cape Town",
    billLandingNo: "BL56473829"
  },
  {
    containerNo: ["UIO1122RT", "WQZ5566PL"],
    importer: "Blessing Efe",
    shippingLine: "MSC",
    examinationAndCustomReleasing: "Pending",
    cosigneeName: "Uche Nwankwo",
    customDocumentation: "Pending",
    portOfDischarge: "Tin Can",
    shippingReleasing: "Uncleared",
    delivery: "Not yet",
    ETA: "2025-07-28",
    status: "In Transit",
    vessel: "MSC Titan",
    billLandingNo: "BL44556677"
  }
];

export default Shipments;
